name: Deploy App to GKE

on:
  push:
    paths:
      - 'K8s/**'
  workflow_dispatch: # Manual trigger enable karega

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GKE Auth
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud config set compute/region ${{ secrets.GCP_REGION }}
          gcloud container clusters get-credentials github-gke-cluster --zone=${{ secrets.GCP_ZONE }}
          gcloud container clusters get-credentials github-gke-cluster --zone ${{ secrets.GCP_ZONE }} --project=${{ secrets.GCP_PROJECT }}

      - name: Deploy App
        run: kubectl apply -f K8s/
